ALTER TABLE public.content_pieces
  ADD COLUMN IF NOT EXISTS phase INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS phase_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS creation_strategy TEXT,
  ADD COLUMN IF NOT EXISTS series_name TEXT,
  ADD COLUMN IF NOT EXISTS series_position INTEGER;